// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klkrexlivtmluosdztxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsa3JleGxpdnRtbHVvc2R6dHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTIwNTMsImV4cCI6MjA3NDIyODA1M30.ZxlNSmVBX7ompk6HyisYmmZJz9GPpHKlaSy5eJKTrew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});